- name: add nginx repo key
  apt_key:
    id: ABF5BD827BD9BF62
    url: http://nginx.org/keys/nginx_signing.key
    state: present

- name: add nginx repo
  apt_repository:
    repo: 'deb http://nginx.org/packages/debian/ {{ ansible_lsb.codename }} nginx'
    state: present
    update_cache: True

- name: installed nginx
  apt:
    name: nginx
    state: installed


- name: clean default file
  template:
    src: default_vhost_config.j2
    dest: /etc/nginx/conf.d/default.conf
    backup: yes
  notify:
    - restart nginx
