- hosts: localhost
  connection: local
  gather_facts: True
  vars_files:
    - vars/cloud.yml
    - vars/database.yml
  roles:
    - cloud/aws/vpc
    - cloud/aws/sg
    - cloud/aws/ec2
    - cloud/aws/rds
