- name: installed zabbix-frontend
  apt:
    name: zabbix-frontend-php
    state: installed

- name: frontend config
  template:
    src: 'zabbix.conf.php.j2'
    dest: '/etc/zabbix/web/zabbix.conf.php'
    backup: yes
