- name: 'add nginx to www-data group'
  user:
    name: nginx
    groups: 'www-data'
    append: yes

- name: 'create nginx vhost zabbix'
  template:
    src: 'nginx-vhost.conf.j2'
    dest: '/etc/nginx/conf.d/zabbix.conf'
    backup: yes
  notify:
    - restart nginx
