- name: installed php-fpm
  apt:
    name: php5-fpm
    state: installed

- name: php zabbix config options
  template:
    src: '99-zabbix.ini.j2'
    dest: '/etc/php5/fpm/conf.d/99-zabbix.ini'
    backup: yes
  notify:
    - restart php-fpm
