- name: i_admin
  ec2:
    key_name: '{{ cloud.aws.key_name }}'
    instance_type: t2.micro
    image: '{{ cloud.aws.ami }}'
    wait: yes
    group: admin
    exact_count: 1
    count_tag:
      role: admin
    region: '{{ cloud.aws.region }}'
    termination_protection: '{{ cloud.aws.termination_protection }}'
    instance_tags:
      role: admin
      Name: admin
