- name: i_blog
  ec2:
    key_name: '{{ cloud.aws.key_name }}'
    instance_type: t2.nano
    image: '{{ cloud.aws.ami }}'
    group_id: '{{ sg_blog_info.group_id }}'
    wait: yes
    exact_count: 1
    count_tag:
      - role: blog
    region: '{{ cloud.aws.region }}'
    termination_protection: '{{ cloud.aws.termination_protection }}'
    instance_tags:
      role: blog
      Name: blog
    vpc_subnet_id: '{{ subnet.id }}'
    assign_public_ip: True
