- include: proxy.yml subnet={{ vpc_info['subnets']|selectattr('resource_tags.Name', 'equalto', 'fiesta')|list|last }}
- include: blog.yml subnet={{ vpc_info['subnets']|selectattr('resource_tags.Name', 'equalto', 'fiesta')|list|last }}
- include: admin.yml subnet={{ vpc_info['subnets']|selectattr('resource_tags.Name', 'equalto', 'fiesta')|list|last }}
- include: monitoring.yml subnet={{ vpc_info['subnets']|selectattr('resource_tags.Name', 'equalto', 'fiesta')|list|last }}
- include: redis.yml subnet={{ vpc_info['subnets']|selectattr('resource_tags.Name', 'equalto', 'fiesta')|list|last }}
