- ec2:
    key_name: '{{ cloud.aws.key_name }}'
    instance_type: t2.nano
    image: '{{ cloud.aws.ami }}'
    wait: yes
    group: monitoring
    count: 1
    region: '{{ cloud.aws.region }}'
    state: present
    termination_protection: yes
    instance_tags:
      role: monitoring
