- name: i_monitoring
  ec2:
    key_name: '{{ cloud.aws.key_name }}'
    instance_type: t2.nano
    image: '{{ cloud.aws.ami }}'
    wait: yes
    group_id: '{{ sg_monitoring_info.group_id }}'
    exact_count: 1
    count_tag:
      role: monitoring
    region: '{{ cloud.aws.region }}'
    termination_protection: '{{ cloud.aws.termination_protection }}'
    instance_tags:
      role: monitoring
      Name: monitoring
    vpc_subnet_id: '{{ subnet.id }}'
    assign_public_ip: True
