- name: i_monitoring
  ec2:
    key_name: '{{ cloud.aws.key_name }}'
    instance_type: t2.nano
    image: '{{ cloud.aws.ami }}'
    wait: yes
    group: monitoring
    exact_count: 1
    count_tag:
      role: monitoring
    region: '{{ cloud.aws.region }}'
    termination_protection: yes
    instance_tags:
      role: monitoring
      Name: monitoring
