- name: i_proxy
  ec2:
    key_name: '{{ cloud.aws.key_name }}'
    instance_type: t2.nano
    image: '{{ cloud.aws.ami }}'
    wait: yes
    group_id: '{{ sg_proxy_info.group_id }}'
    exact_count: 1
    count_tag:
      - role: proxy
    region: '{{ cloud.aws.region }}'
    termination_protection: '{{ cloud.aws.termination_protection }}'
    instance_tags:
      role: proxy
      Name: proxy
    vpc_subnet_id: '{{ subnet.id }}'
    assign_public_ip: True
