- name: i_redis
  ec2:
    key_name: '{{ cloud.aws.key_name }}'
    instance_type: t2.nano
    image: '{{ cloud.aws.ami }}'
    wait: yes
    group: redis
    exact_count: 1
    count_tag:
      role: redis
    region: '{{ cloud.aws.region }}'
    termination_protection: yes
    instance_tags:
      role: redis
      Name: redis
