- name: 'i_proxy facts'
  become: False
  local_action:
    module: ec2_remote_facts
    region: '{{ cloud.aws.region }}'
    filters:
      instance-state-name: running
      'tag:Name': proxy
  register: i_proxy

- debug:
    msg: "{{ i_proxy['instances'][0]['public_dns_name'] }}"

- name: 'i_blog facts'
  become: False
  local_action:
    module: ec2_remote_facts
    region: '{{ cloud.aws.region }}'
    filters:
      instance-state-name: running
      'tag:Name': blog
  register: i_blog

- debug:
    msg: "{{ i_blog['instances'][0]['public_dns_name'] }}"

- name: 'i_admin facts'
  become: False
  local_action:
    module: ec2_remote_facts
    region: '{{ cloud.aws.region }}'
    filters:
      instance-state-name: running
      'tag:Name': blog
  register: i_blog

- debug:
    msg: "{{ i_blog['instances'][0]['public_dns_name'] }}"

- include: nginx.yml
