- name: sg_postgres
  ec2_group:
    name: postgres
    description: postgres
    region: us-east-1
    rules:
      - proto: tcp
        from_port: 5432
        to_port: 5432
        group_name: blog
        group_desc: blog
      - proto: tcp
        from_port: 5432
        to_port: 5432
        group_name: admin
        group_desc: admin
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
    vpc_id: '{{ vpc_info.vpc_id }}'
  register: sg_postgres_info
