- name: create rds_subnet_group
  rds_subnet_group:
    region: '{{ cloud.aws.region }}'
    state: present
    name: '{{ db.name }}'
    description: fiesta
    subnets: "{{ vpc_info['subnets']|selectattr('resource_tags.Name', 'equalto', 'fiesta-db')|map(attribute='id')|list}}"

- name: database
  rds:
    command: create
    instance_name: '{{ db.name }}'
    db_name: '{{ db.name }}'
    db_engine: postgres
    size: 5
    instance_type: db.t2.micro
    username: '{{ db.username }}'
    password: '{{ db.password }}'
    vpc_security_groups: [ '{{ sg_postgres_info.group_id }}' ]
    subnet: '{{ db.name }}'
    multi_zone: no
    region: '{{ cloud.aws.region }}'
    backup_retention: 0
    wait: yes
    wait_timeout: 3600
    tags:
      role: postgres

- rds:
    command: facts
    region: '{{ cloud.aws.region }}'
    instance_name: '{{ db.name }}'
  register: rds

- debug:
   msg: '{{ rds.instance }}'
