- name: Install packages required by the Django app inside virtualenv
  pip:
    virtualenv: '{{ django.virtualenv_path }}'
    requirements: '{{ django.home }}/site/requirements.txt'

- name: django settings
  template:
    src: local_settings.py.j2
    dest: '{{ django.home }}/site/{{ django.app_name }}/local_settings.py'
    backup: yes
  notify:
    - restart gunicorn
