- name: 'i_{{ iname }} facts'
  become: False
  local_action:
    module: ec2_remote_facts
    region: '{{ cloud.aws.region }}'
    filters:
      instance-state-name: running
      'tag:Name': '{{ iname }}'
  register: 'i_{{ iname }}'

- debug:
    msg: 'i_{{ iname }}'

- name: 'rds  facts'
  become: False
  local_action:
    module: rds
    command: facts
    region: '{{ cloud.aws.region }}'
    instance_name: '{{ db.name }}'
  register: rds
  tags:
    - rds

- debug:
   msg: '{{ rds.instance }}'
  tags:
    - rds
