- name: Installed packages
  apt:
    name: '{{ item }}'
    update_cache: yes
    force: yes
    state: installed
  with_items:
    - build-essential
    - python-dev
    - python-pip
    - python-pycurl
    - supervisor
    - virtualenv
    - libpq-dev
